default_language_version:
    python: python3.8
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-docstrings==1.6.0
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.942
    hooks:
      - id: mypy
        additional_dependencies:
          - types-all==1.0.0
          - snowflake-snowpark-python==0.7.0
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.73.0
    hooks:
      - id: terraform_fmt
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 1.2.1
    hooks:
      - id: sqlfluff-fix
      - id: sqlfluff-lint
