SELECT
    record_id,
    metadata_offset::int AS metadata_offset,
    metadata_partition::int AS metadata_partition,
    metadata_topic::varchar AS metadata_topic,
    author::varchar AS author,
    id::varchar AS id,
    saved::boolean AS saved,
    subreddit_type::varchar AS subreddit_type,
    gilded::int AS gilded,
    name::varchar AS name,  -- noqa: L029
    score_hidden::boolean AS score_hidden,
    subreddit_id::varchar AS subreddit_id,
    can_gild::boolean AS can_gild,
    stickied::boolean AS stickied,
    body::varchar AS body,
    replies,
    created_utc::timestamp AS created_utc,
    link_title::varchar AS link_title,
    controversiality::int AS controversiality,
    parent_id::varchar AS parent_id,
    subreddit::varchar AS subreddit,
    archived::boolean AS archived,
    link_id::varchar AS link_id,
    score::int AS score,
    parse_json(metadata_key) AS metadata_key,
    (metadata_create_time::number / 1000)::timestamp AS metadata_create_time,
    parse_url(link_url, 1) AS link_url
FROM flattened_comments;
